name: yaml-practice
services:
    chall:
        container_name: yaml-practice
        build:
            dockerfile: ./deploy/Dockerfile
            context: ../
        logging:
            driver: "json-file"
            options:
                max-size: "50k"
                max-file: "3"
        expose: # This should be the port your challenge runs on inside the container.
            - "8000"
        labels: # please do not delete these labels, if you have a second service make sure the service name and port are replaced
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.b01le.rs`)"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8000" # should match the exposed port
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls={}"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
            # Delete this line, edit and uncomment the lines below to configure rate limiting for your service
            # - "traefik.http.middlewares.ffuf-${COMPOSE_PROJECT_NAME}.ratelimit.average=100"
            # - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=ffuf-${COMPOSE_PROJECT_NAME}"
            # - "traefik.http.middlewares.ffuf-${COMPOSE_PROJECT_NAME}.ratelimit.burst=100"
        ports:
            - "1337:8000"
