name: rustjail
services:
    chall:
        container_name: rustjail
        privileged: true # needed for redpwn jail to work
        build:
            dockerfile: ./deploy/Dockerfile
            context: ../
        logging:
            driver: "json-file"
            options:
                max-size: "50k"
                max-file: "3"
        restart: always
        expose: # This should be the port your challenge runs on inside the container.
            - "6969"
        labels: # please do not delete these labels, if you have a second service make sure the service name and port are replaced
            - "traefik.enable=true"
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}.rule=HostSNI(`${COMPOSE_PROJECT_NAME}.internal-ctf.b01lers.com`)"
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}.tls=true"
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}.entrypoints=ncsecure"
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}-svc"
            - "traefik.tcp.services.${COMPOSE_PROJECT_NAME}-svc.loadbalancer.server.port=6969"
        ports:
            - "1337:6969"
   
